# Generated by Django 3.2.4 on 2021-06-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcrawl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paged',
            name='page',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paged',
            name='link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paged',
            name='pgno',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='paged',
            name='tags',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='paged',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
