# Generated by Django 3.2.4 on 2021-06-09 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcrawl', '0002_auto_20210608_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paged',
            old_name='dt',
            new_name='bgdt',
        ),
        migrations.RenameField(
            model_name='paged',
            old_name='gdt',
            new_name='bgfdt',
        ),
        migrations.RenameField(
            model_name='paged',
            old_name='link',
            new_name='bglink',
        ),
        migrations.RenameField(
            model_name='paged',
            old_name='page',
            new_name='bgpage',
        ),
        migrations.RenameField(
            model_name='paged',
            old_name='read',
            new_name='bgread',
        ),
        migrations.RenameField(
            model_name='paged',
            old_name='tags',
            new_name='bgtags',
        ),
        migrations.RenameField(
            model_name='paged',
            old_name='title',
            new_name='bgtitle',
        ),
    ]
