# Generated by Django 3.2.4 on 2021-06-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcrawl', '0003_auto_20210609_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='pgparam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('num', models.IntegerField()),
            ],
        ),
    ]
