# Generated by Django 3.2.4 on 2021-06-09 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcrawl', '0004_pgparam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='paged',
            new_name='pagedata',
        ),
    ]
