# Generated by Django 3.2.4 on 2021-06-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcrawl', '0005_rename_paged_pagedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='paged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgno', models.CharField(max_length=4)),
                ('bgtitle', models.CharField(max_length=200)),
                ('bgread', models.CharField(max_length=20)),
                ('bgdt', models.CharField(max_length=12)),
                ('bgfdt', models.CharField(max_length=22)),
                ('bglink', models.CharField(max_length=200)),
                ('bgpage', models.CharField(max_length=200, null=True)),
                ('bgtags', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
