# Generated by Django 3.2.4 on 2021-06-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcrawl', '0006_paged'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pagedata',
        ),
    ]
