# Generated by Django 3.2.4 on 2021-06-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcrawl', '0009_pgparam_relatedtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paged',
            name='bgtags',
        ),
        migrations.AddField(
            model_name='paged',
            name='bgtag1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paged',
            name='bgtag2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paged',
            name='bgtag3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paged',
            name='bgtag4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paged',
            name='bgtag5',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
