# Generated by Django 3.2.4 on 2021-06-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcrawl', '0010_auto_20210609_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgparam',
            name='remainingarticles',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pgparam',
            name='subfromtoday',
            field=models.IntegerField(null=True),
        ),
    ]
