# Generated by Django 3.2.4 on 2021-06-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcrawl', '0011_auto_20210610_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgparam',
            name='endnum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pgparam',
            name='startnum',
            field=models.IntegerField(null=True),
        ),
    ]
