# Generated by Django 3.2.4 on 2021-06-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcrawl', '0012_auto_20210610_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgparam',
            name='prevtag',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
    ]
