# Generated by Django 3.2.4 on 2021-06-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcrawl', '0015_rename_code_pgparam_errcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paged',
            name='bgauthor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paged',
            name='bgdt',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='paged',
            name='bgfdt',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='paged',
            name='bgread',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paged',
            name='bgtitle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
