# Generated by Django 3.2.4 on 2021-06-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcrawl', '0016_auto_20210611_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgparam',
            name='scrapetime',
            field=models.FloatField(null=True),
        ),
    ]
