# Generated by Django 3.2.4 on 2021-06-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcrawl', '0017_pgparam_scrapetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgparam',
            name='loopcount',
            field=models.IntegerField(null=True),
        ),
    ]
